spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    username: ${SMTPUSERNAME}
    password: ${SMTPPASSWORD}
    port: ${SMTPPORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true